train_dataset:
  dataset:
    name: image-folder
    args:
      # root_path_1: datafiles/lock3dface_avg_train.txt
      datafile: datafiles/lock3dface_train.txt
      augment: true
      repeat: 1
      # first_k: 220000
      # cache: none
  batch_size: 64

val_dataset:
  dataset:
    name: image-folder
    args:
      # root_path_1: datafiles/lock3dface_avg_test.txt
      datafile: datafiles/lock3dface_test.txt
      augment: false
      # first_k: 10
      repeat: 1
      # cache: in_memory
  batch_size: 64

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
        n_resblocks: 8
    imnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list: [256, 256, 256, 256]
    local_ensemble: False
    feat_unfold: False
    cell_decode: False

# resume: 'save/lock3dface_ori_SR_4_8/epoch-last.pth'
id_net: '/home/rz/code/deep-denoising/save/led3d-experiment/0509-LED3D-SGD-ORI/epoch-best.pth'
id_loss_weight: 0.01

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 100
multi_step_lr:
  # milestones: [200, 400, 600, 800]
  # milestones: [20, 40, 60, 80]
  milestones: [250]
  gamma: 0.5

epoch_val: 1
epoch_save: 200
