train_dataset:
  dataset:
    name: image-folder
    args:
      # root_path_1: datafiles/lock3dface_avg_train.txt
      datafile: datafiles/lock3dface_train.txt
      augment: true
      repeat: 1
      # first_k: 220000
      # cache: none
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 32
      scale_min: 1
      scale_max: 4
      # augment: true
      sample_q: 1024
  batch_size: 128

val_dataset:
  dataset:
    name: image-folder
    args:
      # root_path_1: datafiles/lock3dface_avg_test.txt
      datafile: datafiles/lock3dface_test.txt
      augment: false
      # first_k: 10
      repeat: 1
      # cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 32
      scale_min: 1
      scale_max: 4
      sample_q: 1024
  batch_size: 128

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif-2s
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
        n_resblocks: 8
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256]
    local_ensemble: True
    feat_unfold: True
    cell_decode: True

# resume: 'save/lock3dface_ori_SR_4_8/epoch-last.pth'

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 100
multi_step_lr:
  # milestones: [200, 400, 600, 800]
  # milestones: [20, 40, 60, 80]
  milestones: [250]
  gamma: 0.5

epoch_val: 1
epoch_save: 200
